Добавлен class Message + client и server теперь могут обращаться к библиотеке model
khram2003/BPKproject pull request #2
Opened 2021-02-19 18:42 UTC by alexbuyan

@vasalf можно чекать :)

2021-02-20 08:03 UTC, vasalf requested changes

2021-02-20 08:03 UTC, vasalf commented on CMakeLists.txt
> +include_directories(model model.h)
Здесь папки указываются, не файлы. `model.h` лишний.

2021-02-20 08:03 UTC, vasalf commented on model/model.cpp
> +    tm *Message::utc_time() {
А давайте может быть писать на современных плюсах (`std::chrono`)?

К тому же, тут либо static-функция, либо вообще анонимный неймспейс: зачем этот метод клиентам класса?

2021-02-20 08:03 UTC, vasalf commented on model/model.h
> +        tm *message_time = utc_time();
Не освобождается в деструкторе — очень плохо, память течёт. И лучше std::chrono, в частности, чтобы з аэто не думать.

2021-02-22 21:59 UTC, alexbuyan commented
@vasalf можно смотреть новую версию

2021-02-23 06:59 UTC, vasalf requested changes

2021-02-23 06:59 UTC, vasalf commented on model/model.h
> +            date::floor<date::days>(std::chrono::system_clock::now()));
На моем маке не собирается, потому что эта жуткая константа разная под разнымит системами.

```suggestion
    date::hh_mm_ss<std::chrono::system_clock::duration>
        message_time = date::make_time(
            std::chrono::system_clock::now() -
            date::floor<date::days>(std::chrono::system_clock::now()));
```

2021-02-23 06:59 UTC, vasalf commented on model/model.h
> +    get_message_time() const;
```suggestion
    [[nodiscard]] date::hh_mm_ss<std::chrono::system_clock::duration>
    get_message_time() const;
```

2021-02-23 06:59 UTC, vasalf commented on model/model.cpp
> +date::hh_mm_ss<std::chrono::duration<long long, std::ratio<1, 1000000000>>>
```suggestion
date::hh_mm_ss<std::chrono::system_clock::duration>
```

2021-02-23 10:18 UTC, merged