The last hope to fix git
khram2003/BPKproject pull request #6
Opened 2021-03-01 10:52 UTC by khram2003

2021-03-02 19:54 UTC, vasalf requested changes
Ну, с этим уже точно можно работать, у меня только пара замечаний по файлам и по тому, какие пути как прописаны.

А файлы в `Sprites/` точно должны быть пустые?

2021-03-02 19:54 UTC, vasalf commented on client/CMakeLists.txt
> +list(APPEND CMAKE_PREFIX_PATH "C:\\Qt\\6.0.1\\mingw81_64")
Кажется, этого здесь быть не должно. В идеале этот файл должен собираться на любой системе. Например, на сашином маке или на моей убунте, где, естественно, папки `C:\\` и всех её подпапок нет.

В крайнем случае, для этого можно сделать отдельный файл `config.cmake` и инклудить его сюда. Хорошо бы его в `.gitignore` тогда, а сюда выкладывать только образец.

2021-03-02 19:54 UTC, vasalf commented on client/CMakeLists.txt
> +target_link_libraries(BPK PRIVATE Qt6::Widgets)
```suggestion
target_include_directories(BPK PRIVATE "${CMAKE_BINARY_DIR}/client")
target_link_libraries(BPK PRIVATE Qt6::Widgets)
```

Потому что не всегда оно будет в той же папке. Собирать и хранить исходники в одной папке вообще неудобно — куча лишних файлов, всё засирается, за `.gitignore` думать не успеваешь.

2021-03-02 19:54 UTC, vasalf commented on client/mainwindow.cpp
> +//хочется сделать отдельный класс для сообщения и что нибудь с путями к картинкам
А почему класса из `model/` не хватает?
Мы же писали его туда как раз чтобы ты подсосал и использовал.

2021-03-02 19:54 UTC, vasalf commented on client/mainwindow.cpp
> +    QPixmap sendButtonPixmap("C:/messenger/Sprites/sendButton.png");
Кажется, здесь должен был быть другой путь?

2021-03-02 19:54 UTC, vasalf commented on client/mainwindow.cpp
> +        auto *avatar = new QIcon("C:/messenger/Sprites/qwertyuiop.jpg");
Тут, вероятно, тоже?

2021-03-02 19:54 UTC, vasalf commented on client/mainwindow.cpp
> +        auto *avatar = new QIcon("C:/Users/Никита/Desktop/trash/qwertyuiop.jpg");
И тут?

2021-03-02 19:54 UTC, vasalf commented on client/mainwindow.ui
> +    <height>634</height>
Ради интереса, а эти константы взяты с потолка или имеют какой-то смысл? =)
(править не надо)

2021-03-02 19:54 UTC, vasalf commented on client/messenger.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
А что это за файл? Это типа твои настройки окружения в QtCreator?
Если да, возможно, он скорее нужен в `.gitignore`. Но проверь меня — я такой вывод сделал только по названию, может, тут есть что-то полезное.

2021-03-02 19:54 UTC, vasalf commented on my_branch.txt
> +hi there
Это вроде можно удалить?

2021-03-02 19:54 UTC, vasalf commented on test.txt
> +test text file
Это тоже?

2021-03-04 10:42 UTC, khram2003 commented on test.txt
> +test text file
Будет удалено

2021-03-04 10:43 UTC, khram2003 commented on client/mainwindow.cpp
> +//хочется сделать отдельный класс для сообщения и что нибудь с путями к картинкам
Тут имеется ввиду класс, который будет отвечать за то, как сообщение выглядит.

2021-03-04 10:44 UTC, khram2003 commented on client/CMakeLists.txt
> +list(APPEND CMAKE_PREFIX_PATH "C:\\Qt\\6.0.1\\mingw81_64")
Cmake похоже полностью переделаю

2021-03-04 10:44 UTC, khram2003 commented on client/mainwindow.ui
> +    <height>634</height>
Прикинул  так чтоб красиво было)))

2021-05-04 13:35 UTC, vasalf approved these changes
Он тут долговато висел. Исправь в будущем пути у инклудов?

2021-05-04 13:35 UTC, vasalf commented on client/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} Qt6::Core)
Их можно в одной строке писать, когда их несколько.

2021-05-04 13:35 UTC, vasalf commented on client/src/main.cpp
> +#include "../include/mainwindow.h"
Лучше в угловых скобках и основной путь

2021-05-06 07:40 UTC, merged