test client
khram2003/BPKproject pull request #8
Opened 2021-03-08 21:22 UTC by parseny

2021-04-17 08:03 UTC, vasalf requested changes

2021-04-17 08:03 UTC, vasalf commented on CMakeLists.txt
> +add_subdirectory(third-party/websocketpp-0.8.2)
А как у вас сборка без этого файла работает? https://github.com/zaphoyd/websocketpp/blob/master/cmake/CMakeHelpers.cmake

2021-04-17 08:03 UTC, vasalf commented on client/CMakeLists.txt
> +message(${Boost_LIBRARIES} "Boost")
Это можно убрать, кажется.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +            throw;
Пока сойдëт так делать, наверное. В будущем надо подумать, что мы с этим будем делать. Тут есть какой-то простор для взлома: юзер шлет какой-нибудь неправильный запрос, а у нас от этого сервер тупо падает.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +                std::to_string(user_id) + ", " + std::to_string(chat_id) + ")";
Можно пока забить, но в идеале надо потом подумать про SQL-инъекции.
https://xkcd.com/327/

2021-04-17 08:03 UTC, vasalf commented on client/client.cpp
>  #include <model.h>
Давайте удалим этот файл.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
>  class Database {
Кажется, класс Database пора выносить в отдельный файл `.cpp`.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
>  class Database {
Можно со следующим PR, если сейчас сложновато.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +                    return json{{"user_id", id}, {"user_name", name}}.dump(4);
Опять же, сейчас дампать вот так наверное сойдет (для отладки), но в будущем можно сильно уменьшить сетевой трафик, если дампать без лишних пробелов.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +    [[maybe_unused]] websocketpp::lib::error_code ec = con->get_ec();
Кажется, уже всегда не `unused`?

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +    s->close(hdl, 404, "Websocket closed", ec);
А почему именно 404?
1. Кажется, в любом случае тут не `not found`. Я бы сказал, что тут больше похоже на тупо 400.
2. А тут точно всегда ошибка? Или бывает так, что оно по делу закрывается?

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +        if (msg->get_payload().substr(0, 4) == "echo") {
Я бы что-нибудь посимпатичнее написал. Ну хотя бы набор констант. Типа
```C++
std::string ECHO_CMD = "echo";
std::string FIND_USER_CMD = "find_user";
// и так далее
if (msg->get_payload().substr(0, ECHO_CMD.size()) == "echo") {
    s->send(hdl, msg->get_payload().substr(ECHO_CMD.size() + 1), msg->get_opcode());
} else if (...) {
    // и так далее
}
```

Как минимум чтобы не совершить тут случайную ошибку с неправильной длиной строки.

Можно тут замутить что-нибудь ещë симпатичнее, с каким-нибудь классом-обработчиком, у которого есть маппинг между строками и функциями обработки, но это уже опционально, особенно в нашей текущей ситуации.

2021-04-17 08:03 UTC, vasalf commented on server/server.cpp
> +    database.add_message(1, recipient_id, sender_id, text);
А это ныне происходит каждый раз, когда сервер запускается? Если сервер упал и перезапустился, там две копии сообщений будет в этом чате?

Не имею ничего против, но вероятно довольно скоро вы захотите это убрать =)

2021-04-17 10:30 UTC, alexbuyan commented on server/server.cpp
> +    database.add_message(1, recipient_id, sender_id, text);
Это мы тестировали database, проверяли что у Арсения запускается и работает. Так, конечно, уберем

2021-04-17 10:31 UTC, alexbuyan commented on client/client.cpp
>  #include <model.h>
Типо вообще не будем использовать class Message?

2021-04-17 10:32 UTC, alexbuyan commented on server/server.cpp
> +            throw;
Думал об этом, но пока нет дельных мыслей, можно обсудить на созвоне

2021-04-17 10:34 UTC, alexbuyan commented on client/CMakeLists.txt
> +message(${Boost_LIBRARIES} "Boost")
Вроде как client без этого не собирается. То есть к примеру у меня, когда я запускал client.cpp, и в CMake не было boost, ничего не работало. Как подключил, все стало ок. Возможно, когда мы перепишем client.cpp, необходимости в этом не будет

2021-04-17 10:35 UTC, alexbuyan commented on CMakeLists.txt
> +add_subdirectory(third-party/websocketpp-0.8.2)
Хм, интересно...

2021-04-17 10:36 UTC, alexbuyan commented on server/server.cpp
>  class Database {
Согласен, но видимо в следующем PR уже

2021-04-17 10:37 UTC, alexbuyan commented on server/server.cpp
> +                    return json{{"user_id", id}, {"user_name", name}}.dump(4);
Вообще я сделал .dump(4) чисто для красоты вывода, но если Никита сможет и без дампа распарсить запрос, и это уменьшит сетевой трафик, то можем убрать

2021-04-17 10:39 UTC, alexbuyan commented on server/server.cpp
> +    s->close(hdl, 404, "Websocket closed", ec);
Тут я, честно, не знаю как ответить. Видимо не всегда должен быть code 404, и не всегда с ошибкой закрывается (но это мое предположение)

2021-04-17 10:41 UTC, alexbuyan commented on server/server.cpp
> +        if (msg->get_payload().substr(0, 4) == "echo") {
Константы добавим, ок

2021-04-18 07:18 UTC, vasalf commented on client/CMakeLists.txt
> +message(${Boost_LIBRARIES} "Boost")
Вот именно эта строчка просто отладочны вывод. `find_package` при этом нужен.

2021-04-18 07:18 UTC, vasalf commented on client/client.cpp
>  #include <model.h>
Нет, я про файл `client/client.cpp`.

2021-04-18 07:18 UTC, vasalf commented on server/server.cpp
> +                    return json{{"user_id", id}, {"user_name", name}}.dump(4);
Сможет, уменьшит. Но можно пока оставить.

2021-04-20 21:58 UTC, parseny commented on server/server.cpp
> +                std::to_string(user_id) + ", " + std::to_string(chat_id) + ")";
![image](https://user-images.githubusercontent.com/71630904/115468882-64559580-a23c-11eb-8ac4-203e595ed71a.png)

2021-04-25 14:43 UTC, vasalf commented on client/CMakeLists.txt
> +message(${Boost_LIBRARIES} "Boost")
Не убрано. Ладно, вмëржим.

2021-04-25 14:46 UTC, vasalf commented on client/CMakeLists.txt
> +message(${Boost_LIBRARIES} "Boost")
Я прошу прощения. Не туда посмотрел. Все ок.

2021-04-25 14:47 UTC, merged